# conda env create -f environment-cpu.yml
name: ctlearn
channels:
    - anaconda
dependencies:
    - python=3.7
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - tensorflow=2.1.0
