# conda env create -f environment-cpu.yml
name: ctlearn
channels:
    - anaconda
    - bryankim96
    - conda-forge
    - cta-observatory
dependencies:
    - python=3.7.3
    - dl1_data_handler
    - matplotlib
    - numpy
    - pandas
    - pip
    # TensorFlow-CPU v1.13.1:
    - pip:
        - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.13.1-cp37-cp37m-linux_x86_64.whl
    - pyyaml
    - scikit-learn
