# conda env create -f environment-cpu.yml
name: ctlearn
channels:
    - anaconda
dependencies:
    - python=3.7.3
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        # TensorFlow-CPU v1.13.1
        - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.13.1-cp37-cp37m-linux_x86_64.whl
