# conda env create -f environment-macos.yml
name: ctlearn
channels:
    - anaconda
    - bryankim96
    - conda-forge
    - cta-observatory
dependencies:
    - python=3.7.3
    - dl1_data_handler
    - matplotlib
    - numpy
    - pandas
    - pip
    # TensorFlow-CPU v1.12.0:
    - pip:
        - https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl
    - pyyaml
    - scikit-learn
