# conda env create -f environment-gpu.yml
name: ctlearn
channels:
    - anaconda
dependencies:
    - python=3.7.3
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        # TensorFlow-GPU v1.13.1
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.13.1-cp37-cp37m-linux_x86_64.whl
