# conda env create -f environment-gpu.yml
name: ctlearn
channels:
    - anaconda
dependencies:
    - python=3.7
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
     pip:
        # TensorFlow-GPU v2.1.0
        - https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.13.1-py3-none-any.whl
